### ISSUE TITLE
Disable strapdown on the index HTML table?

### ISSUE THREAD

**Issue by Naereen** [chuckhoupt/autoindex_strapdown#1] opened 2015-11-22 11:07 UTC
Hi!

First, _whoa_, awesome project, it works well and it looks amazing, thanks :clap: !!

Secondly, do you know if we could either disable the strapdown conversion on the HTML table generated by Apache, or at least try to fix that bug:
#### Nice feature or nasty bug?

I [tested](http://perso.crans.org/besson/autoindex_strapdown/) with filenames containing Markdown markup syntax (`__`, `**`, `*`, `~~` and code):

```
bugged--**this_is_bold**.txt  → ~ OK
bugged--*this_is_emph*.txt  → ~ OK
bugged--__this_is_bold__.txt  → NOT OK
bugged--``this_is_code``.txt  → ~ OK
bugged--~~this_is_striked~~.txt  → ~ OK
```

See in this screenshot how they look like:

> ![autoindex_strapdown_bug](https://cloud.githubusercontent.com/assets/11994719/11323304/e86d0ebe-910f-11e5-9bb6-b0ab666dc45d.png)

It's really fine, the links are all good, but for one file, the HTML table gets messed up.
If a filename contains one `__`, apparently it breaks the validity of the generated HTML table. Uhh...

See here another example (it's again a `__` which messed up the code):
![autoindex_strapdown_bug2](https://cloud.githubusercontent.com/assets/11994719/11323361/db79ff18-9110-11e5-82c2-4cca58798424.png)

---

I am used to StrapDown.js, but do not know how we could fix this. Any idea?
Thanks in advance!

**Comment by chuckhoupt** [comment] 2015-11-25 13:47
Thanks for finding this bug -- I think the problem is with the markd package inside StrapDown.js. I'll try testing with a newer version.

**Comment by Naereen** [comment] 2015-12-10 08:22
Hi.
Have you tried?

**Comment by chuckhoupt** [comment] 2015-12-12 00:42
Sorry for the delay. I had forgotten Jedi Master Yoda's words -- there is no try...

So the problem is in [markd](https://github.com/chjj/marked/) -- it (incorrectly) defaults to rendering markdown in HTML blocks. However, it has an option to turn the enhancement off. Unfortunately, it looks like it can only be fixed in StrapDown.js -- there's no way to pass the option from autoindex_strapdown.

So on a fork, I've added the option: https://github.com/chuckhoupt/strapdown/commit/1a090729fb717059be0689aa65025de6de67b3cd

If you're self-hosting, you could replace your local strapdown.js with the new 0.2p version for immediate relief: https://github.com/chuckhoupt/strapdown/blob/pedantic-markd/v/0.2p/strapdown.js#L419

Tomorrow, I'll look into applying the change to the ais.habilis.net hosted files.

**Comment by Naereen** [comment] 2015-12-12 11:12
Hi,
It works really fine. Thanks !
I haven't tried myself to tweak [marked](https://github.com/chjj/marked/), good job for finding the good option.

On the [tests showed](http://perso.crans.org/besson/autoindex_strapdown/) previously, it's now fixed:
![autoindex_strapdown__bug1_fixed](https://cloud.githubusercontent.com/assets/11994719/11761604/56135dd8-a0c9-11e5-9f24-753b43c7dcd3.png)

**Comment by Naereen** [comment] 2015-12-13 12:13
For my [own version of StrapDown.js](https://github.com/Naereen/StrapDown.js), [I just added an option](https://github.com/Naereen/StrapDown.js/commit/287d2540c0ee8ace3002a07c741b707f7f1c1436#diff-9e060af2251f3de88aade944b3058044R478) that can be given when loading the script.

Loading `strapdown.min.js` does not set `pedantic=true` (so, as before), and `strapdown.min.js?pedantic=y` turn on the pedantic mode (and it looks well, cf. [this example](http://perso.crans.org/besson/autoindex_strapdown/)).

Allowing to disable the pedantic mode is useful, to easily mix Markdown and HTML.
For instance, as StrapDown.js brings the awesome bootstrap CSS, it can be used to improve style of a paragraph in a Markdown document.
Example:
![example_strapdown_improve_style_of_a_div](https://cloud.githubusercontent.com/assets/11994719/11766910/3a44f6b6-a19b-11e5-800a-860325dd699e.png)

**Comment by chuckhoupt** [comment] 2015-12-13 13:28
That's a nifty way to handle it. Another way might be to use classes to signal the options. Like:

``` html
<xmp class="markd-pedantic">
  ...pedantic markdown...
</xmp>
```

**Closed as completed** 2016-05-26 16:25 UTC
